# Generated by Django 2.0 on 2019-01-02 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='厂商名称')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='支持电话')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '厂商',
                'verbose_name_plural': '厂商',
            },
        ),
        migrations.CreateModel(
            name='sbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbb_type', models.SmallIntegerField(choices=[(0, '测酒仪'), (1, '模拟机'), (2, '验卡器'), (3, '读卡器'), (4, '自助出退勤'), (5, '其他')], default=0, verbose_name='设备类型')),
                ('name', models.CharField(max_length=64, verbose_name='设备编号')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='固资编码')),
                ('manage_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='远控ID')),
                ('purchase_day', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expire_day', models.DateField(blank=True, null=True, verbose_name='年检日期')),
                ('chunqiu_day', models.DateField(blank=True, null=True, verbose_name='春鉴/秋整日期')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '设备总表',
                'verbose_name_plural': '设备总表',
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Shudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='属地')),
                ('pname', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('pnober', models.CharField(blank=True, max_length=64, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '属地',
                'verbose_name_plural': '属地',
            },
        ),
        migrations.AddField(
            model_name='sbb',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbb.Shudi', verbose_name='属地'),
        ),
        migrations.AddField(
            model_name='sbb',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbb.Manufacturer', verbose_name='设备制造商'),
        ),
    ]
