# Generated by Django 2.0 on 2019-01-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbb', '0002_sbb_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbb',
            old_name='name',
            new_name='bianhao',
        ),
    ]
