# Generated by Django 2.0 on 2019-01-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbb', '0004_sbb_gz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='img')),
            ],
        ),
    ]
